name: CI (using deno)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x # Run with latest stable Deno

      - name: Check if already formatted
        run: deno fmt --check
        
      - name: Lint 
        run: deno lint

      - name: Test
        run: deno test