name: Deploy to npm

on: 
  release:
    types: [published]

jobs:
  typedoc:
    name: TypeDoc
    runs-on: ubuntu-latest # Ubuntuの最新版を実行環境とする
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js (v18.3.0)
        uses: actions/setup-node@v3
        with:
          node-version: '18.3.0'
      - name: Dependencies
        run: npm ci
      - name: TypeDoc
        run: npm deploy
