name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/v2.')
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish
